### ISSUE TITLE
Invalid utf8mb4 character string: 'ACED00'

### ISSUE THREAD

**Issue by xHyroM** [ZorTik/AdvancedSQLClient#28]
```
[20:40:25 WARN]: java.sql.SQLException: Invalid utf8mb4 character string: 'ACED00'
[20:40:25 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
[20:40:25 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[20:40:25 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
[20:40:25 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972)
[20:40:25 WARN]:        at KetchupEconomy-1.0.0-all.jar//me.zort.sqllib.SQLDatabaseConnectionImpl.query(SQLDatabaseConnectionImpl.java:279)
[20:40:25 WARN]:        at KetchupEconomy-1.0.0-all.jar//me.zort.sqllib.SQLDatabaseConnectionImpl.query(SQLDatabaseConnectionImpl.java:268)
[20:40:25 WARN]:        at KetchupEconomy-1.0.0-all.jar//me.zort.sqllib.SQLDatabaseConnectionImpl.query(SQLDatabaseConnectionImpl.java:251)
[20:40:25 WARN]:        at KetchupEconomy-1.0.0-all.jar//me.zort.sqllib.internal.query.QueryNodeRequest.lambda$obtainAll$1(QueryNodeRequest.java:41)
[20:40:25 WARN]:        at KetchupEconomy-1.0.0-all.jar//me.zort.sqllib.internal.query.QueryNode.invokeToConnection(QueryNode.java:102)
[20:40:25 WARN]:        at KetchupEconomy-1.0.0-all.jar//me.zort.sqllib.internal.query.QueryNodeRequest.obtainAll(QueryNodeRequest.java:41)
[20:40:25 WARN]:        at KetchupEconomy-1.0.0-all.jar//me.zort.sqllib.internal.query.QueryNodeRequest.obtainOne(QueryNodeRequest.java:29)
[20:40:25 WARN]:        at KetchupEconomy-1.0.0-all.jar//dev.xhyrom.keconomy.structs.PlayerWrapper.loadSync(PlayerWrapper.java:39)
[20:40:25 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[20:40:25 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[20:40:25 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:40:25 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[20:40:25 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[20:40:25 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

```java
package dev.xhyrom.keconomy.storage.structs;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;
import me.zort.sqllib.internal.annotation.PrimaryKey;

@AllArgsConstructor
public class PlayerBalance {
    @PrimaryKey
    private String uuid;
    @Getter
    @Setter
    private double balance;
}
```

**Comment by ZorTik** [comment]
This issue occured when putting invalid statement input value. Only supported types should be provided.
